services:
  rest-api:
    build:
      context: .
      dockerfile: ./src/api/Dockerfile
    command: uvicorn api.main:app --host 0.0.0.0 --port 5000
    volumes:
      - ./.env:/rest-api/.env
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
        - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

networks:
    app-network:
        driver: bridge

volumes:
    postgres_data:
